export const labels: Record<string, string> = {
  not_started: "Sin iniciar",
  preparation: "En preparación",
  review: "En revisión",
  ready_to_close: "Lista para cerrar",
  closed: "Cerrada",
  changes_detected: "Con novedades",
  reopened: "Reabierta",
  blocked: "Bloqueada",
  documents_reviewed: "Documentos revisados",
  exclusions_reasoned: "Exclusiones con motivo",
  sources_settled: "Fuentes resueltas al corte",
  integrity_resolved: "Archivos rechazados e incidencias revisados",
  relationships_reviewed:
    "Relaciones, cancelaciones y advertencias PPD revisadas",
  scope_confirmed: "Alcance de revisión confirmado",
  snapshot_ready: "Información preparada para cierre",
  client_clarifications: "Aclaraciones del cliente documentadas",
  professional_review: "Revisión del responsable",
  open: "Abierta",
  client_clarification: "Pendiente de aclaración con el cliente",
  resolved: "Resuelta",
  reviewed_rejection: "Rechazo revisado",
  pending: "Por revisar",
  reviewed: "Revisada",
  included: "Incluida",
  excluded: "Excluida",
  waiting_sat: "SAT está procesando",
  requires_user_authorization: "Requiere nueva autorización",
  external_submission_unknown: "Envío SAT sin respuesta confirmada",
  completed: "Completado",
  completed_with_issues: "Completado con incidencias",
  queued: "En espera",
  processing: "En proceso",
  authorization_pending: "Autorización pendiente",
  cancelled: "Cancelado",
  failed: "Fallido",
};
export const label = (x: string) => labels[x] ?? x;
