import Link from "next/link";
import { AlertTriangle, FileText, Plus, UserRoundCog } from "lucide-react";
import { CfdiActions } from "@/components/cfdi-actions";
import { ActionDialog, DetailDrawer } from "@/components/overlay-dialog";
import { DefinitionGrid, FeaturePendingNotice, Field, FilterBar, ProgressValue, SectionTabs, Surface, SurfaceHeader, WarningNotice } from "@/components/product-patterns";
import { ProductTable } from "@/components/product-table";
import { ReturnLink } from "@/components/return-link";
import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { clientById, demoData } from "@/lib/demo-data";
import { clientBase } from "@/lib/nav";

const selectClass = "h-10 rounded-md border border-input bg-card px-3 text-body-sm";
const money = new Intl.NumberFormat("es-MX", { style: "currency", currency: "MXN" });

function ClientTitle({ organizationId, clientId, eyebrow, title, description, actions }: { organizationId: string; clientId: string; eyebrow: string; title: string; description: string; actions?: React.ReactNode }) {
  const client = clientById(organizationId, clientId)!;
  return <header className="flex flex-col gap-4 border-l-2 border-brand-mark pl-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-caption font-semibold text-accent-foreground">{eyebrow}</p><h1 className="text-heading-lg font-bold">{title}</h1><p className="mt-1 text-body text-muted-foreground">{description}</p><p className="identifier mt-2 text-caption text-muted-foreground">{client.name} · RFC {client.rfc}</p></div>{actions ? <div className="flex flex-wrap gap-2">{actions}</div> : null}</header>;
}

export function ClientOverviewScreen({ organizationId, clientId }: { organizationId: string; clientId: string }) {
  const client = clientById(organizationId, clientId)!;
  const base = clientBase("es", organizationId, clientId);
  const actions = <><CfdiActions clientName={client.name} periodLabel={client.currentPeriod} includeExport={false} /><DetailDrawer trigger={<Button variant="outline"><UserRoundCog />Cambiar responsable</Button>} title="Cambiar responsable" description="Asignación explícita para este cliente"><div className="space-y-5"><FeaturePendingNotice>La asignación no se guardará hasta integrar membresías y autorización del backend.</FeaturePendingNotice><Field label="Nuevo responsable"><select className={`${selectClass} w-full`} defaultValue="mariana"><option value="mariana">Mariana Torres</option><option value="angel">Ángel Ruiz</option><option value="lucia">Lucía Soto</option></select></Field><Button className="w-full" disabled>Guardar asignación</Button></div></DetailDrawer></>;
  return <div className="space-y-6"><ClientTitle organizationId={organizationId} clientId={clientId} eyebrow="Cliente" title="Resumen del cliente" description="Estado operativo, vigencia de credenciales y trabajo pendiente del período actual." actions={actions} /><DefinitionGrid items={[{ label: "Período actual", value: client.currentPeriod }, { label: "Estado", value: <StatusBadge status={client.status} /> }, { label: "Avance", value: `${client.progress}%` }, { label: "Último corte SAT", value: client.lastCutoff }, { label: "e.firma", value: <StatusBadge status={client.eSignature} /> }, { label: "Conexión SAT", value: <StatusBadge status={client.satConnection} /> }, { label: "CFDI nuevos", value: 18 }, { label: "Incidencias", value: client.incidents }]} /><div className="grid gap-6 xl:grid-cols-[1.4fr_1fr]"><Surface><SurfaceHeader title="Ejercicio 2026" description="Avance de los doce períodos." actions={<Button render={<Link href={`${base}/ejercicios/2026`} />} variant="outline">Abrir ejercicio</Button>} /><div className="p-5"><ProgressValue value={67} label="Avance anual" /><div className="mt-5 grid grid-cols-4 gap-2 sm:grid-cols-6">{demoData.periods.map((period) => <Link key={period.slug} href={`${base}/ejercicios/2026/periodos/${period.slug}/resumen`} className="rounded-md border border-border p-2 text-center hover:bg-muted"><span className="block text-caption font-semibold">{period.month.slice(0, 3)}</span><span className="numeric text-caption text-muted-foreground">{period.progress}%</span></Link>)}</div></div></Surface><Surface><SurfaceHeader title="Atención requerida" description="Eventos que bloquean o cambian la preparación." /><div className="divide-y divide-border"><Link href={`${base}/alertas`} className="flex min-h-14 items-center gap-3 p-4 hover:bg-muted"><AlertTriangle className="size-5 text-warning" /><span><span className="block font-semibold">3 incidencias abiertas</span><span className="text-caption text-muted-foreground">Una es bloqueante para el cierre</span></span></Link><Link href={`${base}/obligaciones`} className="flex min-h-14 items-center gap-3 p-4 hover:bg-muted"><FileText className="size-5 text-info" /><span><span className="block font-semibold">DIOT con observaciones</span><span className="text-caption text-muted-foreground">Agosto 2026</span></span></Link></div></Surface></div><Surface><SurfaceHeader title="Acciones rápidas" /><div className="flex flex-wrap gap-2 p-5"><Button render={<Link href={`${base}/ejercicios/2026/periodos/08/resumen`} />}>Abrir período actual</Button><Button render={<Link href={`${base}/cfdi`} />} variant="outline">Revisar CFDI</Button><Button render={<Link href={`${base}/obligaciones`} />} variant="outline">Obligaciones fiscales</Button></div></Surface></div>;
}

export function FiscalYearsScreen({ organizationId, clientId }: { organizationId: string; clientId: string }) {
  const base = clientBase("es", organizationId, clientId);
  const rows = [{ year: "2026", status: "En revisión", closed: 5, pending: 7, news: 1, activity: "18 ago 2026" }, { year: "2025", status: "Cerrado", closed: 12, pending: 0, news: 0, activity: "16 ene 2026" }];
  return <div className="space-y-6"><ClientTitle organizationId={organizationId} clientId={clientId} eyebrow="Ejercicios fiscales" title="Ejercicios" description="Compara avance, pendientes y novedades antes de abrir un año." actions={<ActionDialog trigger={<Button><Plus />Nuevo ejercicio</Button>} title="Crear ejercicio" description="El ejercicio se asociaría al cliente activo." confirmLabel="Crear ejercicio"><FeaturePendingNotice>No existe servicio para persistir ejercicios.</FeaturePendingNotice><Field label="Año"><Input type="number" defaultValue="2027" /></Field></ActionDialog>} /><Surface><ProductTable caption="Ejercicios fiscales" rows={rows} rowKey={(row) => row.year} columns={[{ id: "year", header: "Año", render: (row) => <Link href={`${base}/ejercicios/${row.year}`} className="font-semibold text-primary hover:underline">{row.year}</Link> }, { id: "status", header: "Estado", render: (row) => <StatusBadge status={row.status} /> }, { id: "closed", header: "Períodos cerrados", numeric: true, render: (row) => row.closed }, { id: "pending", header: "Pendientes", numeric: true, render: (row) => row.pending }, { id: "news", header: "Novedades", numeric: true, render: (row) => row.news }, { id: "activity", header: "Última actividad", render: (row) => row.activity }, { id: "action", header: "Acción", render: (row) => <Button render={<Link href={`${base}/ejercicios/${row.year}`} />} variant="outline" size="sm">Abrir ejercicio</Button> }]} /></Surface></div>;
}

export function FiscalYearScreen({ organizationId, clientId, year }: { organizationId: string; clientId: string; year: string }) {
  const base = clientBase("es", organizationId, clientId);
  return <div className="space-y-6"><ClientTitle organizationId={organizationId} clientId={clientId} eyebrow="Ejercicio fiscal" title={`Ejercicio ${year}`} description="Los doce períodos se muestran en una tabla compacta para facilitar la comparación." /><Surface><ProductTable caption={`Períodos del ejercicio ${year}`} rows={demoData.periods} rowKey={(row) => row.slug} columns={[{ id: "month", header: "Mes", render: (row) => <Link href={`${base}/ejercicios/${year}/periodos/${row.slug}/resumen`} className="font-semibold text-primary hover:underline">{row.month}</Link> }, { id: "status", header: "Estado", render: (row) => <StatusBadge status={row.status} /> }, { id: "progress", header: "Avance", render: (row) => <ProgressValue value={row.progress} /> }, { id: "cfdi", header: "CFDI", numeric: true, render: (row) => row.cfdi }, { id: "incidents", header: "Incidencias", numeric: true, render: (row) => row.incidents }, { id: "cutoff", header: "Fecha de corte", render: (row) => row.cutoff }, { id: "version", header: "Versión", render: (row) => row.version }, { id: "responsible", header: "Responsable", render: (row) => row.responsible }, { id: "action", header: "Acción", render: (row) => <Button render={<Link href={`${base}/ejercicios/${year}/periodos/${row.slug}/resumen`} />} variant="outline" size="sm">Abrir</Button> }]} /></Surface></div>;
}

export function ClientCfdiScreen({ organizationId, clientId }: { organizationId: string; clientId: string }) {
  const client = clientById(organizationId, clientId)!;
  const base = clientBase("es", organizationId, clientId);
  const rows = demoData.cfdi.filter((item) => item.clientId === clientId);
  const returnTo = encodeURIComponent(`${base}/cfdi?estado=pendiente&metodo=PPD`);
  return <div className="space-y-6"><ClientTitle organizationId={organizationId} clientId={clientId} eyebrow="Consulta transversal" title="CFDI" description="Consulta documentos del cliente y conserva los filtros en la URL al abrir un detalle." actions={<CfdiActions clientName={client.name} periodLabel="Todos los períodos" exportScope="Resultados filtrados" />} /><Surface><FilterBar><Field label="Buscar"><Input defaultValue="" placeholder="UUID, RFC o folio" className="w-64" /></Field><Field label="Vista"><select className={selectClass}><option>Todos</option><option>Emitidos</option><option>Recibidos</option></select></Field><Field label="Método"><select className={selectClass}><option>Todos</option><option>PUE</option><option>PPD</option></select></Field><Field label="Estado"><select className={selectClass}><option>Todos</option><option>Pendiente</option><option>Con incidencia</option></select></Field></FilterBar><ProductTable caption="CFDI del cliente" rows={rows} rowKey={(row) => row.uuid} columns={[{ id: "uuid", header: "UUID", render: (row) => <Link href={`${base}/cfdi/${row.uuid}?returnTo=${returnTo}`} className="identifier font-semibold text-primary hover:underline">{row.uuid}</Link> }, { id: "date", header: "Fecha", render: (row) => row.date }, { id: "direction", header: "Dirección", render: (row) => row.direction }, { id: "type", header: "Tipo", render: (row) => row.type }, { id: "counterparty", header: "Contraparte", render: (row) => <div><p>{row.name}</p><p className="identifier text-caption text-muted-foreground">{row.rfc}</p></div> }, { id: "method", header: "Método", render: (row) => row.method }, { id: "total", header: "Total", numeric: true, render: (row) => money.format(row.total) }, { id: "status", header: "Estado", render: (row) => <StatusBadge status={row.status} /> }, { id: "action", header: "Acción", render: (row) => <Button render={<Link href={`${base}/cfdi/${row.uuid}?returnTo=${returnTo}`} />} variant="outline" size="sm">Abrir detalle</Button> }]} /></Surface><FeaturePendingNotice>Los filtros son estructura visual. La consulta usa fixtures locales y no representa una descarga del SAT.</FeaturePendingNotice></div>;
}

export function CfdiDetailScreen({ organizationId, clientId, uuid }: { organizationId: string; clientId: string; uuid: string }) {
  const base = clientBase("es", organizationId, clientId);
  const item = demoData.cfdi.find((candidate) => candidate.clientId === clientId && candidate.uuid === uuid)!;
  return <div className="space-y-6"><ReturnLink fallback={`${base}/cfdi`} label="Volver a CFDI" /><ClientTitle organizationId={organizationId} clientId={clientId} eyebrow="Detalle de CFDI" title={item.uuid} description="Vista legible del documento demostrativo y las decisiones internas del despacho." actions={<ActionDialog trigger={<Button variant="outline">Excluir con motivo</Button>} title="Excluir CFDI" description="La exclusión requiere motivo y trazabilidad." confirmLabel="Excluir CFDI"><FeaturePendingNotice>No se modificará el documento demo.</FeaturePendingNotice><Field label="Motivo"><select className={selectClass}><option>Documento ajeno al período</option><option>Duplicado</option><option>Otro</option></select></Field><Field label="Comentario"><Input placeholder="Describe el criterio" /></Field></ActionDialog>} /><DefinitionGrid items={[{ label: "Tipo", value: item.type }, { label: "Dirección", value: item.direction }, { label: "Estado", value: <StatusBadge status={item.status} /> }, { label: "Total", value: money.format(item.total) }, { label: "Fecha", value: item.date }, { label: "Método", value: item.method }, { label: "Complemento", value: item.paymentComplement }, { label: "Origen", value: "Fixture demostrativo" }]} /><Surface><SectionTabs active="datos" items={[{ id: "datos", label: "Datos generales", href: `${base}/cfdi/${uuid}` }, { id: "xml", label: "XML", href: `${base}/cfdi/${uuid}?vista=xml` }, { id: "conceptos", label: "Conceptos", href: `${base}/cfdi/${uuid}?vista=conceptos` }, { id: "impuestos", label: "Impuestos", href: `${base}/cfdi/${uuid}?vista=impuestos` }, { id: "relaciones", label: "Relaciones", href: `${base}/cfdi/${uuid}?vista=relaciones` }, { id: "historial", label: "Historial", href: `${base}/cfdi/${uuid}?vista=historial` }]} /><div className="grid gap-5 p-5 sm:grid-cols-2"><div><p className="text-caption font-semibold text-muted-foreground">Emisor/receptor</p><p className="mt-1 font-semibold">{item.name}</p><p className="identifier text-body-sm">{item.rfc}</p></div><div><p className="text-caption font-semibold text-muted-foreground">Decisión del despacho</p><p className="mt-1 text-body-sm">Pendiente de revisión manual; no existe clasificación persistida.</p></div></div></Surface><WarningNotice>El XML completo no se muestra en datos demo y nunca debe exponerse en auditoría.</WarningNotice></div>;
}

export function ClientAlertsScreen({ organizationId, clientId }: { organizationId: string; clientId: string }) {
  const alerts = [{ id: "al1", type: "PPD sin complemento", severity: "Bloqueante", context: "DEMO-7C10-31B2-80A4", responsible: "Mariana Torres", date: "18 ago 2026", status: "Pendiente" }, { id: "al2", type: "e.firma próxima a vencer", severity: "Advertencia", context: "Credenciales SAT", responsible: "Mariana Torres", date: "17 ago 2026", status: "En revisión" }, { id: "al3", type: "Novedad posterior al cierre", severity: "Advertencia", context: "Abril 2026", responsible: "Ángel Ruiz", date: "16 ago 2026", status: "Pendiente" }];
  return <div className="space-y-6"><ClientTitle organizationId={organizationId} clientId={clientId} eyebrow="Seguimiento" title="Alertas" description="Agrupa incidencias que requieren atención sin comunicar severidad sólo mediante color." /><Surface><ProductTable caption="Alertas del cliente" rows={alerts} rowKey={(row) => row.id} columns={[{ id: "type", header: "Tipo", render: (row) => <span className="font-semibold">{row.type}</span> }, { id: "severity", header: "Severidad", render: (row) => <StatusBadge status={row.severity} /> }, { id: "context", header: "Contexto", render: (row) => <span className="identifier">{row.context}</span> }, { id: "responsible", header: "Responsable", render: (row) => row.responsible }, { id: "date", header: "Fecha", render: (row) => row.date }, { id: "status", header: "Estado", render: (row) => <StatusBadge status={row.status} /> }, { id: "action", header: "Acción", render: (row) => <DetailDrawer trigger={<Button variant="outline" size="sm">Revisar</Button>} title={row.type} description={row.context}><DefinitionGrid items={[{ label: "Severidad", value: row.severity }, { label: "Estado", value: row.status }, { label: "Responsable", value: row.responsible }, { label: "Fecha", value: row.date }]} /><FeaturePendingNotice>El detalle de incidencia no está conectado a un servicio.</FeaturePendingNotice></DetailDrawer> }]} /></Surface></div>;
}

const clientSettingsCopy: Record<string, { title: string; description: string }> = {
  datos: { title: "Datos del cliente", description: "Identidad fiscal y datos operativos básicos." },
  responsables: { title: "Responsables", description: "Asignaciones explícitas de miembros al cliente." },
  "e-firma-sat": { title: "e.firma y SAT", description: "Credenciales y vigencia; nunca se muestran secretos." },
  obligaciones: { title: "Obligaciones", description: "Configuración declarada del cliente sin determinación automática." },
  accesos: { title: "Accesos", description: "Miembros y capacidades aplicables al cliente." },
};

export function ClientSettingsScreen({ organizationId, clientId, section = "datos" }: { organizationId: string; clientId: string; section?: string }) {
  const client = clientById(organizationId, clientId)!;
  const base = clientBase("es", organizationId, clientId);
  const copy = clientSettingsCopy[section] ?? clientSettingsCopy.datos;
  const tabs = [{ id: "datos", label: "Datos", href: `${base}/configuracion/datos` }, { id: "responsables", label: "Responsables", href: `${base}/configuracion/responsables` }, { id: "e-firma-sat", label: "e.firma y SAT", href: `${base}/configuracion/e-firma-sat` }, { id: "obligaciones", label: "Obligaciones", href: `${base}/configuracion/obligaciones` }, { id: "accesos", label: "Accesos", href: `${base}/configuracion/accesos` }];
  return <div className="space-y-6"><ClientTitle organizationId={organizationId} clientId={clientId} eyebrow="Configuración del cliente" title={copy.title} description={copy.description} /><Surface><SectionTabs items={tabs} active={section} /><div className="space-y-5 p-5"><FeaturePendingNotice>Los cambios no se persisten y las capacidades visuales no sustituyen autorización del backend.</FeaturePendingNotice>{section === "e-firma-sat" ? <DefinitionGrid items={[{ label: "Estado", value: <StatusBadge status={client.eSignature} /> }, { label: "Conexión SAT", value: <StatusBadge status={client.satConnection} /> }, { label: "Titular del certificado", value: "Información protegida" }, { label: "Vencimiento", value: "18 sep 2026 (demo)" }]} /> : section === "responsables" || section === "accesos" ? <ProductTable caption="Asignaciones demostrativas" rows={[{ id: "r1", name: "Mariana Torres", role: "Titular", access: "Asignación explícita" }, { id: "r2", name: "Ángel Ruiz", role: "Contador responsable", access: "Operación y cierre" }]} rowKey={(row) => row.id} columns={[{ id: "name", header: "Miembro", render: (row) => row.name }, { id: "role", header: "Perfil", render: (row) => row.role }, { id: "access", header: "Acceso", render: (row) => row.access }, { id: "action", header: "Acción", render: () => <Button variant="outline" size="sm"><UserRoundCog />Cambiar responsable</Button> }]} /> : <div className="grid max-w-form gap-5 sm:grid-cols-2"><Field label="Razón social"><Input defaultValue={client.name} /></Field><Field label="RFC"><Input defaultValue={client.rfc} className="identifier" /></Field><Field label="Responsable"><Input defaultValue={client.responsible} /></Field><Field label="Período actual"><Input defaultValue={client.currentPeriod} /></Field></div>}<div className="flex justify-end"><Button disabled>Guardar cambios</Button></div></div></Surface></div>;
}
