import Link from "next/link";
import { FileCog, FileText, Settings } from "lucide-react";
import { ActionDialog } from "@/components/overlay-dialog";
import { DefinitionGrid, FeaturePendingNotice, Field, SectionTabs, Surface, WarningNotice } from "@/components/product-patterns";
import { ProductTable } from "@/components/product-table";
import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { clientById } from "@/lib/demo-data";
import { clientBase } from "@/lib/nav";

const selectClass = "h-10 rounded-md border border-input bg-card px-3 text-body-sm";
const money = new Intl.NumberFormat("es-MX", { style: "currency", currency: "MXN" });

function ObligationTitle({ organizationId, clientId, eyebrow, title, description, actions }: { organizationId: string; clientId: string; eyebrow: string; title: string; description: string; actions?: React.ReactNode }) {
  const client = clientById(organizationId, clientId)!;
  return <header className="flex flex-col gap-4 border-l-2 border-brand-mark pl-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-caption font-semibold text-accent-foreground">{eyebrow}</p><h1 className="text-heading-lg font-bold">{title}</h1><p className="mt-1 text-body text-muted-foreground">{description}</p><p className="identifier mt-2 text-caption text-muted-foreground">{client.name} · RFC {client.rfc}</p></div>{actions ? <div className="flex flex-wrap gap-2">{actions}</div> : null}</header>;
}

function obligationTabs(base: string, active: string) {
  return <SectionTabs active={active} items={[{ id: "overview", label: "Resumen", href: `${base}/obligations` }, { id: "diot", label: "DIOT", href: `${base}/obligations/diot` }, { id: "ieps", label: "IEPS", href: `${base}/obligations/ieps` }, { id: "files", label: "Archivos generados", href: `${base}/obligations/generated-files` }]} />;
}

export function ObligationsScreen({ organizationId, clientId }: { organizationId: string; clientId: string }) {
  const base = clientBase("es", organizationId, clientId);
  const rows = [{ id: "o1", obligation: "DIOT", frequency: "Mensual", period: "Agosto 2026", status: "Con observaciones", observations: 4, file: "Versión 1 desactualizada", responsible: "Mariana Torres", href: `${base}/obligations/diot/2026/08/overview` }, { id: "o2", obligation: "IEPS · Anexo 1", frequency: "Mensual", period: "Agosto 2026", status: "Pendiente", observations: 2, file: "Sin archivo", responsible: "Ángel Ruiz", href: `${base}/obligations/ieps/ieps-anexo-1-2026-08/overview` }];
  return <div className="space-y-6"><ObligationTitle organizationId={organizationId} clientId={clientId} eyebrow="Cliente" title="Obligaciones fiscales" description="Prepara información y archivos sin presentar declaraciones ni determinar obligaciones automáticamente." /><Surface>{obligationTabs(base, "overview")}<ProductTable caption="Obligaciones configuradas" rows={rows} rowKey={(row) => row.id} columns={[{ id: "obligation", header: "Obligación", render: (row) => <Link href={row.href} className="font-semibold text-primary hover:underline">{row.obligation}</Link> }, { id: "frequency", header: "Periodicidad", render: (row) => row.frequency }, { id: "period", header: "Período", render: (row) => row.period }, { id: "status", header: "Estado", render: (row) => <StatusBadge status={row.status} /> }, { id: "observations", header: "Observaciones", numeric: true, render: (row) => row.observations }, { id: "file", header: "Último archivo", render: (row) => row.file }, { id: "responsible", header: "Responsable", render: (row) => row.responsible }, { id: "action", header: "Acción", render: (row) => <Button render={<Link href={row.href} />} variant="outline" size="sm">Continuar</Button> }]} /></Surface><WarningNotice>Estos estados son demostrativos. Hemia no presenta declaraciones ni obtiene acuses en esta implementación.</WarningNotice></div>;
}

export function DiotListScreen({ organizationId, clientId }: { organizationId: string; clientId: string }) {
  const base = clientBase("es", organizationId, clientId);
  const rows = [{ id: "d08", period: "Agosto 2026", cutoff: "18 ago 2026", providers: 42, operations: 186, status: "Con observaciones", file: "v1 · Desactualizada", href: `${base}/obligations/diot/2026/08/overview` }, { id: "d07", period: "Julio 2026", cutoff: "06 ago 2026", providers: 39, operations: 204, status: "Generada", file: "v2 · Vigente", href: `${base}/obligations/diot/2026/07/overview` }];
  return <div className="space-y-6"><ObligationTitle organizationId={organizationId} clientId={clientId} eyebrow="Obligaciones fiscales" title="DIOT" description="Control mensual de preparación, validaciones y versiones de archivo." /><Surface>{obligationTabs(base, "diot")}<ProductTable caption="Períodos DIOT" rows={rows} rowKey={(row) => row.id} columns={[{ id: "period", header: "Período", render: (row) => <Link href={row.href} className="font-semibold text-primary hover:underline">{row.period}</Link> }, { id: "cutoff", header: "Fecha de corte", render: (row) => row.cutoff }, { id: "providers", header: "Proveedores", numeric: true, render: (row) => row.providers }, { id: "operations", header: "Operaciones", numeric: true, render: (row) => row.operations }, { id: "status", header: "Estado", render: (row) => <StatusBadge status={row.status} /> }, { id: "file", header: "Último archivo", render: (row) => row.file }, { id: "action", header: "Acción", render: (row) => <Button render={<Link href={row.href} />} variant="outline" size="sm">Abrir período</Button> }]} /></Surface></div>;
}

const diotTabLabels: Record<string, string> = { resumen: "Resumen", operaciones: "Operaciones", validaciones: "Validaciones", ajustes: "Ajustes", "preview": "Vista previa", archivos: "Archivos" };

export function DiotPeriodScreen({ organizationId, clientId, year, period, tab }: { organizationId: string; clientId: string; year: string; period: string; tab: string }) {
  const base = clientBase("es", organizationId, clientId);
  const root = `${base}/obligations/diot/${year}/${period}`;
  const tabs = Object.entries(diotTabLabels).map(([id, label]) => ({ id, label, href: `${root}/${id}` }));
  const action = <ActionDialog trigger={<Button><FileText />Generar archivo DIOT</Button>} title="Generar archivo DIOT" description="Revisa layout, período y observaciones antes de solicitar el archivo." confirmLabel="Generar archivo DIOT"><FeaturePendingNotice>La generación TXT y la presentación ante el SAT están fuera de alcance. No se producirá un archivo.</FeaturePendingNotice><Field label="Layout"><select className={selectClass}><option>Layout demostrativo 2026</option></select></Field><Field label="Período"><Input value="Agosto 2026" readOnly /></Field></ActionDialog>;
  return <div className="space-y-6"><ObligationTitle organizationId={organizationId} clientId={clientId} eyebrow="DIOT · Agosto 2026" title={diotTabLabels[tab]} description="Estructura de preparación con columnas representativas, no reglas fiscales definitivas." actions={action} /><Surface><SectionTabs items={tabs} active={tab} /><div className="p-5">{renderDiotTab(tab)}</div></Surface></div>;
}

function renderDiotTab(tab: string) {
  if (tab === "overview") return <DefinitionGrid items={[{ label: "Período", value: "Agosto 2026" }, { label: "Fecha de corte", value: "18 ago 2026" }, { label: "CFDI considerados", value: 186 }, { label: "Proveedores", value: 42 }, { label: "Total de operaciones", value: money.format(1284500.75) }, { label: "IVA identificado", value: money.format(164820.1) }, { label: "Registros pendientes", value: 4 }, { label: "Estado", value: <StatusBadge status="Con observaciones" /> }]} />;
  if (tab === "operations") {
    const rows = [{ id: "op1", rfc: "DEM070707GG7", name: "Proveedora Horizonte Demo", third: "Nacional", operation: "Servicios", value: 240000, vat: 38400, withheld: 0, creditable: 32000, nonCreditable: 6400, status: "Revisado" }, { id: "op2", rfc: "DEM080808HH8", name: "Insumos del Centro Demo", third: "Nacional", operation: "Otros", value: 89500, vat: 14320, withheld: 0, creditable: 0, nonCreditable: 14320, status: "Pendiente" }];
    return <ProductTable caption="Operaciones representativas DIOT" rows={rows} rowKey={(row) => row.id} columns={[{ id: "rfc", header: "RFC", render: (row) => <span className="identifier">{row.rfc}</span> }, { id: "name", header: "Razón social", render: (row) => row.name }, { id: "third", header: "Tipo de tercero", render: (row) => row.third }, { id: "operation", header: "Operación", render: (row) => row.operation }, { id: "value", header: "Valor de actos", numeric: true, render: (row) => money.format(row.value) }, { id: "vat", header: "IVA trasladado", numeric: true, render: (row) => money.format(row.vat) }, { id: "withheld", header: "IVA retenido", numeric: true, render: (row) => money.format(row.withheld) }, { id: "creditable", header: "IVA acreditable", numeric: true, render: (row) => money.format(row.creditable) }, { id: "non-creditable", header: "IVA no acreditable", numeric: true, render: (row) => money.format(row.nonCreditable) }, { id: "status", header: "Estado", render: (row) => <StatusBadge status={row.status} /> }]} />;
  }
  if (tab === "validations") {
    const rows = [{ id: "v1", issue: "Proveedor sin clasificación", records: 2, severity: "Bloqueante", status: "Pendiente" }, { id: "v2", issue: "Pago no determinado", records: 1, severity: "Advertencia", status: "En revisión" }, { id: "v3", issue: "Dato capturado manualmente", records: 1, severity: "Información", status: "Revisado" }];
    return <ProductTable caption="Validaciones DIOT" rows={rows} rowKey={(row) => row.id} columns={[{ id: "issue", header: "Validación", render: (row) => <span className="font-semibold">{row.issue}</span> }, { id: "records", header: "Registros", numeric: true, render: (row) => row.records }, { id: "severity", header: "Severidad", render: (row) => <StatusBadge status={row.severity} /> }, { id: "status", header: "Estado", render: (row) => <StatusBadge status={row.status} /> }, { id: "action", header: "Acción", render: () => <Button variant="outline" size="sm">Revisar</Button> }]} />;
  }
  if (tab === "adjustments") {
    const rows = [{ id: "aj1", field: "IVA acreditable", original: 0, adjusted: 14320, reason: "Clasificación manual pendiente de confirmar", user: "Mariana Torres", date: "18 ago 2026" }];
    return <ProductTable caption="Ajustes DIOT" rows={rows} rowKey={(row) => row.id} columns={[{ id: "field", header: "Campo", render: (row) => row.field }, { id: "original", header: "Valor original", numeric: true, render: (row) => money.format(row.original) }, { id: "adjusted", header: "Valor ajustado", numeric: true, render: (row) => money.format(row.adjusted) }, { id: "reason", header: "Motivo", render: (row) => row.reason }, { id: "user", header: "Usuario", render: (row) => row.user }, { id: "date", header: "Fecha", render: (row) => row.date }]} />;
  }
  if (tab === "preview") return <div className="space-y-5"><WarningNotice>Esta vista tabular sólo representa el contenido potencial. No es un TXT oficial ni implementa un layout SAT.</WarningNotice><DefinitionGrid items={[{ label: "Layout seleccionado", value: "Demostrativo 2026" }, { label: "Registros", value: 42 }, { label: "Advertencias", value: 4 }, { label: "Estado", value: <StatusBadge status="Con observaciones" /> }]} /><pre className="overflow-x-auto rounded-lg border border-border bg-muted p-4 text-caption">DEM070707GG7 | Nacional | Servicios | 240000.00 | 38400.00{`\n`}DEM080808HH8 | Nacional | Otros | 89500.00 | 14320.00</pre></div>;
  const rows = [{ id: "f1", version: "v1", layout: "Demostrativo 2026", date: "17 ago 2026", user: "Mariana Torres", period: "Agosto 2026", records: 40, status: "Desactualizada" }];
  return <ProductTable caption="Versiones DIOT" rows={rows} rowKey={(row) => row.id} columns={[{ id: "version", header: "Versión", render: (row) => row.version }, { id: "layout", header: "Layout", render: (row) => row.layout }, { id: "date", header: "Fecha", render: (row) => row.date }, { id: "user", header: "Usuario", render: (row) => row.user }, { id: "period", header: "Período", render: (row) => row.period }, { id: "records", header: "Registros", numeric: true, render: (row) => row.records }, { id: "status", header: "Vigencia", render: (row) => <StatusBadge status={row.status} /> }, { id: "action", header: "Acción", render: () => <Button variant="outline" size="sm" disabled>Descargar</Button> }]} />;
}

export function IepsListScreen({ organizationId, clientId }: { organizationId: string; clientId: string }) {
  const base = clientBase("es", organizationId, clientId);
  const rows = [{ id: "ieps-anexo-1-2026-08", name: "IEPS · Anexo 1 · Agosto 2026", frequency: "Mensual", status: "Pendiente", detected: 12, pending: 3, responsible: "Ángel Ruiz" }, { id: "ieps-anexo-2-2026-q3", name: "IEPS · Anexo 2 · Tercer trimestre 2026", frequency: "Trimestral", status: "En preparación", detected: 8, pending: 1, responsible: "Mariana Torres" }];
  return <div className="space-y-6"><ObligationTitle organizationId={organizationId} clientId={clientId} eyebrow="Obligaciones fiscales" title="Informativas IEPS" description="Configura obligaciones específicas antes de preparar una instancia; no existe un generador universal." actions={<ActionDialog trigger={<Button><Settings />Configurar informativas IEPS</Button>} title="Configurar informativas IEPS" description="Define obligaciones declaradas por el despacho." confirmLabel="Guardar configuración"><FeaturePendingNotice>No se determinarán obligaciones automáticamente.</FeaturePendingNotice><Field label="Tipo de actividad"><Input placeholder="Actividad demostrativa" /></Field><Field label="Anexo"><select className={selectClass}><option>Anexo 1</option><option>Anexo 2</option></select></Field><Field label="Periodicidad"><select className={selectClass}><option>Mensual</option><option>Trimestral</option></select></Field></ActionDialog>} /><Surface>{obligationTabs(base, "ieps")}<ProductTable caption="Instancias IEPS" rows={rows} rowKey={(row) => row.id} columns={[{ id: "name", header: "Instancia", render: (row) => <Link href={`${base}/obligations/ieps/${row.id}/overview`} className="font-semibold text-primary hover:underline">{row.name}</Link> }, { id: "frequency", header: "Periodicidad", render: (row) => row.frequency }, { id: "status", header: "Estado", render: (row) => <StatusBadge status={row.status} /> }, { id: "detected", header: "Impuestos detectados", numeric: true, render: (row) => row.detected }, { id: "pending", header: "Pendientes", numeric: true, render: (row) => row.pending }, { id: "responsible", header: "Responsable", render: (row) => row.responsible }, { id: "action", header: "Acción", render: (row) => <Button render={<Link href={`${base}/obligations/ieps/${row.id}/overview`} />} variant="outline" size="sm">Abrir</Button> }]} /></Surface></div>;
}

const iepsTabLabels: Record<string, string> = { resumen: "Resumen", "source-cfdi": "CFDI fuente", impuestos: "Impuestos IEPS detectados", productos: "Productos y conceptos", clasificacion: "Clasificación", "additional-information": "Información adicional", validaciones: "Validaciones", "preview": "Vista previa", archivos: "Archivos" };

export function IepsInstanceScreen({ organizationId, clientId, instanceId, tab }: { organizationId: string; clientId: string; instanceId: string; tab: string }) {
  const base = clientBase("es", organizationId, clientId);
  const root = `${base}/obligations/ieps/${instanceId}`;
  const tabs = Object.entries(iepsTabLabels).map(([id, label]) => ({ id, label, href: `${root}/${id}` }));
  const action = <ActionDialog trigger={<Button><FileCog />Generar archivo batch para MULTI-IEPS</Button>} title="Generar archivo batch para MULTI-IEPS" description="Revisa configuración, anexo y validaciones." confirmLabel="Generar archivo batch"><FeaturePendingNotice>No se generará TXT, archivo .dec, acuse ni presentación fiscal.</FeaturePendingNotice><Field label="Anexo"><Input value="Anexo 1" readOnly /></Field><Field label="Layout"><select className={selectClass}><option>Versión demostrativa 2026</option></select></Field></ActionDialog>;
  return <div className="space-y-6"><ObligationTitle organizationId={organizationId} clientId={clientId} eyebrow="IEPS · Anexo 1 · Agosto 2026" title={iepsTabLabels[tab]} description="Preparación documental de una instancia configurada." actions={action} /><FeaturePendingNotice>El archivo TXT estaría preparado para importarse en el aplicativo MULTI-IEPS. Hemia no presenta la declaración ni genera automáticamente el acuse del SAT.</FeaturePendingNotice><Surface><SectionTabs items={tabs} active={tab} /><div className="p-5">{renderIepsTab(tab)}</div></Surface></div>;
}

function renderIepsTab(tab: string) {
  if (tab === "overview") return <DefinitionGrid items={[{ label: "Obligación", value: "Anexo 1" }, { label: "Periodicidad", value: "Mensual" }, { label: "Período", value: "Agosto 2026" }, { label: "Estado", value: <StatusBadge status="Pendiente" /> }, { label: "CFDI fuente", value: 26 }, { label: "Impuestos detectados", value: 12 }, { label: "Pendientes de clasificar", value: 3 }, { label: "Responsable", value: "Ángel Ruiz" }]} />;
  const rows = tab === "validations" ? [{ id: "i1", concept: "Producto sin categoría IEPS", source: "DEMO-8F2A-44C1-91B0", value: "3 conceptos", status: "Pendiente" }, { id: "i2", concept: "Tasa por confirmar", source: "DEMO-7C10-31B2-80A4", value: "1 concepto", status: "En revisión" }] : [{ id: "i1", concept: "Producto demostrativo A", source: "DEMO-8F2A-44C1-91B0", value: money.format(45800), status: "Pendiente" }, { id: "i2", concept: "Producto demostrativo B", source: "DEMO-7C10-31B2-80A4", value: money.format(21600), status: "Revisado" }];
  if (tab === "preview") return <div className="space-y-5"><WarningNotice>Vista tabular demostrativa. No corresponde a un layout oficial ni genera un archivo importable.</WarningNotice><DefinitionGrid items={[{ label: "Layout", value: "Demostrativo 2026" }, { label: "Anexo", value: "1" }, { label: "Registros", value: 12 }, { label: "Advertencias", value: 3 }]} /></div>;
  if (tab === "files") return <ProductTable caption="Archivos batch IEPS" rows={[]} rowKey={(row: { id: string }) => row.id} columns={[{ id: "version", header: "Versión", render: () => "" }, { id: "layout", header: "Layout", render: () => "" }, { id: "date", header: "Fecha", render: () => "" }, { id: "status", header: "Estado", render: () => "" }]} emptyMessage="No hay archivos batch generados. La integración funcional está pendiente." />;
  return <ProductTable caption={iepsTabLabels[tab]} rows={rows} rowKey={(row) => row.id} columns={[{ id: "concept", header: tab === "validations" ? "Validación" : "Producto o concepto", render: (row) => <span className="font-semibold">{row.concept}</span> }, { id: "source", header: "CFDI fuente", render: (row) => <span className="identifier">{row.source}</span> }, { id: "value", header: "Información", render: (row) => row.value }, { id: "status", header: "Estado", render: (row) => <StatusBadge status={row.status} /> }, { id: "action", header: "Acción", render: () => <Button variant="outline" size="sm">Revisar</Button> }]} />;
}

export function GeneratedFilesScreen({ organizationId, clientId }: { organizationId: string; clientId: string }) {
  const base = clientBase("es", organizationId, clientId);
  const rows = [{ id: "gf1", type: "DIOT", period: "Agosto 2026", annex: "No aplica", layout: "Demostrativo 2026", version: "v1", date: "17 ago 2026", requester: "Mariana Torres", status: "Desactualizada", validity: "Cambió información fuente" }];
  return <div className="space-y-6"><ObligationTitle organizationId={organizationId} clientId={clientId} eyebrow="Obligaciones fiscales" title="Archivos generados" description="Vista transversal de versiones y vigencia; la descarga sólo se habilita con un recurso real autorizado." /><Surface>{obligationTabs(base, "files")}<ProductTable caption="Archivos fiscales generados" rows={rows} rowKey={(row) => row.id} columns={[{ id: "type", header: "Tipo", render: (row) => row.type }, { id: "period", header: "Período", render: (row) => row.period }, { id: "annex", header: "Anexo", render: (row) => row.annex }, { id: "layout", header: "Layout", render: (row) => row.layout }, { id: "version", header: "Versión", render: (row) => row.version }, { id: "date", header: "Fecha", render: (row) => row.date }, { id: "requester", header: "Solicitante", render: (row) => row.requester }, { id: "status", header: "Estado", render: (row) => <StatusBadge status={row.status} /> }, { id: "validity", header: "Vigencia", render: (row) => row.validity }, { id: "action", header: "Acción", render: () => <Button variant="outline" size="sm" disabled>Descargar</Button> }]} /></Surface></div>;
}
