import Link from "next/link";
import { CheckCircle2, FileArchive } from "lucide-react";
import { CfdiActions } from "@/components/cfdi-actions";
import { ActionDialog, DetailDrawer } from "@/components/overlay-dialog";
import { DefinitionGrid, FeaturePendingNotice, Field, FilterBar, ProgressValue, SectionTabs, Surface, SurfaceHeader, WarningNotice } from "@/components/product-patterns";
import { ProductTable } from "@/components/product-table";
import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { clientById, demoData } from "@/lib/demo-data";
import { clientBase } from "@/lib/nav";

const selectClass = "h-10 rounded-md border border-input bg-card px-3 text-body-sm";
const money = new Intl.NumberFormat("es-MX", { style: "currency", currency: "MXN" });
const tabLabels: Record<string, string> = { resumen: "Resumen", cfdi: "CFDI", pagos: "Pagos", nomina: "Nómina", incidencias: "Incidencias", cierre: "Checklist y cierre", exportaciones: "Exportaciones" };

export function PeriodScreen({ organizationId, clientId, year, period, tab }: { organizationId: string; clientId: string; year: string; period: string; tab: string }) {
  const client = clientById(organizationId, clientId)!;
  const periodData = demoData.periods.find((item) => item.slug === period)!;
  const base = `${clientBase("es", organizationId, clientId)}/ejercicios/${year}/periodos/${period}`;
  const tabs = Object.entries(tabLabels).map(([id, label]) => ({ id, label, href: `${base}/${id}` }));
  const actions = <CfdiActions clientName={client.name} periodLabel={`${periodData.month} ${year}`} exportScope="Todo el período" />;
  return <div className="space-y-6"><header className="flex flex-col gap-4 border-l-2 border-brand-mark pl-4 xl:flex-row xl:items-start xl:justify-between"><div><p className="text-caption font-semibold text-accent-foreground">Período contable</p><h1 className="text-heading-lg font-bold">{client.name}</h1><div className="mt-1 flex flex-wrap items-center gap-2"><span className="text-body text-muted-foreground">{periodData.month} {year}</span><span aria-hidden="true">·</span><StatusBadge status={periodData.status} /></div><p className="mt-2 text-caption text-muted-foreground">Último corte SAT: {periodData.cutoff} · Responsable: {periodData.responsible} · Versión: {periodData.version}</p></div><div className="flex flex-wrap gap-2">{actions}</div></header><Surface><SectionTabs items={tabs} active={tab} /><div className="p-5">{renderPeriodTab(tab, organizationId, clientId, year, period, periodData.status)}</div></Surface></div>;
}

function renderPeriodTab(tab: string, organizationId: string, clientId: string, year: string, period: string, status: string) {
  const clientRoot = clientBase("es", organizationId, clientId);
  const cfdiRows = demoData.cfdi.filter((item) => item.clientId === clientId);
  if (tab === "resumen") return <div className="space-y-6"><DefinitionGrid items={[{ label: "Nuevos", value: 18 }, { label: "Revisados", value: 192 }, { label: "Pendientes", value: 31 }, { label: "Excluidos", value: 3 }, { label: "Con incidencias", value: 3 }, { label: "Emitidos", value: 141 }, { label: "Recibidos", value: 103 }, { label: "Estado de cierre", value: <StatusBadge status={status} /> }]} /><div className="grid gap-6 lg:grid-cols-2"><Surface><SurfaceHeader title="Checklist" description="7 de 10 controles completados." /><div className="p-5"><ProgressValue value={70} label="Checklist completado" /><Button render={<Link href={`${clientRoot}/ejercicios/${year}/periodos/${period}/cierre`} />} variant="outline" className="mt-4">Continuar checklist</Button></div></Surface><Surface><SurfaceHeader title="Obligaciones del período" /><div className="divide-y divide-border"><Link href={`${clientRoot}/obligaciones/diot/${year}/${period}/resumen`} className="flex min-h-14 items-center justify-between p-4 hover:bg-muted"><span><span className="block font-semibold">DIOT</span><span className="text-caption text-muted-foreground">Continuar preparación</span></span><StatusBadge status="Con observaciones" /></Link><Link href={`${clientRoot}/obligaciones/ieps/ieps-anexo-1-${year}-${period}/resumen`} className="flex min-h-14 items-center justify-between p-4 hover:bg-muted"><span><span className="block font-semibold">IEPS · Anexo 1</span><span className="text-caption text-muted-foreground">Revisar información</span></span><StatusBadge status="Pendiente" /></Link></div></Surface></div></div>;
  if (tab === "cfdi") return <div className="space-y-4"><FilterBar><Field label="Vista"><select className={selectClass}><option>Todos</option><option>Emitidos</option><option>Recibidos</option></select></Field><Field label="Método"><select className={selectClass}><option>Todos</option><option>PPD</option><option>PUE</option></select></Field><ActionDialog trigger={<Button variant="outline">Aplicar acción masiva</Button>} title="Aplicar acción masiva" description="La acción afectaría únicamente la selección visible." confirmLabel="Aplicar acción"><FeaturePendingNotice>No se modificará ningún CFDI.</FeaturePendingNotice><Field label="Acción"><select className={selectClass}><option>Marcar revisado</option><option>Clasificar</option><option>Excluir con motivo</option></select></Field></ActionDialog></FilterBar><ProductTable caption="CFDI del período" rows={cfdiRows} rowKey={(row) => row.uuid} columns={[{ id: "select", header: "Seleccionar", render: (row) => <input type="checkbox" aria-label={`Seleccionar ${row.uuid}`} className="size-5 accent-primary" /> }, { id: "uuid", header: "UUID", render: (row) => <Link href={`${clientRoot}/cfdi/${row.uuid}?returnTo=${encodeURIComponent(`${clientRoot}/ejercicios/${year}/periodos/${period}/cfdi`)}`} className="identifier font-semibold text-primary hover:underline">{row.uuid}</Link> }, { id: "type", header: "Tipo", render: (row) => `${row.direction} · ${row.type}` }, { id: "counterparty", header: "Contraparte", render: (row) => row.name }, { id: "method", header: "Método", render: (row) => row.method }, { id: "total", header: "Total", numeric: true, render: (row) => money.format(row.total) }, { id: "status", header: "Estado", render: (row) => <StatusBadge status={row.status} /> }, { id: "action", header: "Acción", render: (row) => <ActionDialog trigger={<Button variant="outline" size="sm">Excluir</Button>} title="Excluir CFDI con motivo" description={row.uuid} confirmLabel="Excluir CFDI"><FeaturePendingNotice>La exclusión no se persistirá.</FeaturePendingNotice><Field label="Motivo"><Input placeholder="Describe el criterio" /></Field></ActionDialog> }]} /></div>;
  if (tab === "pagos") {
    const rows = cfdiRows.filter((item) => item.method === "PPD");
    return <ProductTable caption="Complementos y relaciones de pago" rows={rows} rowKey={(row) => row.uuid} columns={[{ id: "uuid", header: "CFDI", render: (row) => <span className="identifier">{row.uuid}</span> }, { id: "counterparty", header: "Contraparte", render: (row) => row.name }, { id: "total", header: "Importe", numeric: true, render: (row) => money.format(row.total) }, { id: "complement", header: "Complemento", render: (row) => <StatusBadge status={row.paymentComplement} /> }, { id: "relations", header: "Relaciones", render: (row) => row.paymentComplement === "Pendiente" ? "Relación incompleta" : "Documentos relacionados" }, { id: "action", header: "Acción", render: (row) => <Button render={<Link href={`${clientRoot}/cfdi/${row.uuid}`} />} variant="outline" size="sm">Abrir CFDI</Button> }]} />;
  }
  if (tab === "nomina") return <div className="space-y-5"><FeaturePendingNotice>La pestaña está protegida por <span className="identifier">payroll.view</span>. No realiza cálculo de nómina.</FeaturePendingNotice><ProductTable caption="CFDI de nómina" rows={cfdiRows.filter((item) => item.type === "Nómina")} rowKey={(row) => row.uuid} columns={[{ id: "uuid", header: "UUID", render: (row) => <span className="identifier">{row.uuid}</span> }, { id: "date", header: "Fecha", render: (row) => row.date }, { id: "employer", header: "Emisor", render: (row) => row.name }, { id: "total", header: "Total", numeric: true, render: (row) => money.format(row.total) }, { id: "status", header: "Estado", render: (row) => <StatusBadge status={row.status} /> }]} /></div>;
  if (tab === "incidencias") {
    const rows = [{ id: "inc-1", type: "PPD sin complemento", severity: "Bloqueante", context: "DEMO-7C10-31B2-80A4", responsible: "Mariana Torres", status: "Pendiente", date: "18 ago 2026" }, { id: "inc-2", type: "RFC por confirmar", severity: "Advertencia", context: "DEMO-6B09-22A3-72D8", responsible: "Ángel Ruiz", status: "En revisión", date: "17 ago 2026" }];
    return <ProductTable caption="Incidencias del período" rows={rows} rowKey={(row) => row.id} columns={[{ id: "type", header: "Tipo", render: (row) => <span className="font-semibold">{row.type}</span> }, { id: "severity", header: "Severidad", render: (row) => <StatusBadge status={row.severity} /> }, { id: "context", header: "CFDI o contexto", render: (row) => <span className="identifier">{row.context}</span> }, { id: "responsible", header: "Responsable", render: (row) => row.responsible }, { id: "status", header: "Estado", render: (row) => <StatusBadge status={row.status} /> }, { id: "date", header: "Fecha", render: (row) => row.date }, { id: "action", header: "Acción", render: (row) => <DetailDrawer trigger={<Button variant="outline" size="sm">Revisar</Button>} title={row.type} description={row.context}><DefinitionGrid items={[{ label: "Severidad", value: row.severity }, { label: "Responsable", value: row.responsible }, { label: "Estado", value: row.status }, { label: "Fecha", value: row.date }]} /><FeaturePendingNotice>No existe servicio de incidencias.</FeaturePendingNotice></DetailDrawer> }]} />;
  }
  if (tab === "cierre") return <div className="space-y-6"><WarningNotice>El cierre corresponde al control interno del despacho y no representa la presentación de una declaración fiscal.</WarningNotice><div className="space-y-2">{["CFDI revisados", "Incidencias bloqueantes resueltas", "Complementos de pago revisados", "Obligaciones del período revisadas", "Exportación de respaldo preparada"].map((item, index) => <label key={item} className="flex min-h-11 items-center gap-3 rounded-md border border-border px-4"><input type="checkbox" defaultChecked={index < 3} className="size-5 accent-primary" /><span className="flex-1">{item}</span>{index < 3 ? <CheckCircle2 className="size-4 text-success" aria-label="Completado" /> : null}</label>)}</div><div className="flex flex-wrap gap-2"><ActionDialog trigger={<Button>Confirmar cierre</Button>} title="Confirmar cierre interno" description="Se crearía una versión del control mensual." confirmLabel="Cerrar período"><FeaturePendingNotice>No se cerrará el período ni se generará una versión real.</FeaturePendingNotice><Field label="Comentario de cierre"><Input placeholder="Contexto del cierre" /></Field></ActionDialog><ActionDialog trigger={<Button variant="outline">Reabrir con motivo</Button>} title="Reabrir período" description="La reapertura requiere capacidad y trazabilidad." confirmLabel="Reabrir período"><FeaturePendingNotice>No se modificará el estado demo.</FeaturePendingNotice><Field label="Motivo"><Input placeholder="Explica por qué debe reabrirse" /></Field></ActionDialog></div></div>;
  const exports = [{ id: "exp-1", format: "XLSX", scope: "CFDI revisados", requested: "17 ago 2026", status: "Completado", expires: "24 ago 2026" }, { id: "exp-2", format: "ZIP XML", scope: "Todo el período", requested: "18 ago 2026", status: "En proceso", expires: "—" }];
  return <div className="space-y-5"><ActionDialog trigger={<Button><FileArchive />Configurar exportación</Button>} title="Configurar exportación" description="Selecciona formato y alcance." confirmLabel="Generar exportación"><FeaturePendingNotice>No se generará ni descargará un archivo.</FeaturePendingNotice><Field label="Formato"><select className={selectClass}><option>Excel (.xlsx)</option><option>CSV</option><option>ZIP de XML</option></select></Field></ActionDialog><ProductTable caption="Historial de exportaciones" rows={exports} rowKey={(row) => row.id} columns={[{ id: "format", header: "Formato", render: (row) => row.format }, { id: "scope", header: "Alcance", render: (row) => row.scope }, { id: "requested", header: "Solicitud", render: (row) => row.requested }, { id: "status", header: "Estado", render: (row) => <StatusBadge status={row.status} /> }, { id: "expires", header: "Expira", render: (row) => row.expires }, { id: "action", header: "Acción", render: () => <Button variant="outline" size="sm" disabled>Descargar</Button> }]} /></div>;
}
