const CANONICAL_FISCAL_ERROR_CODES: ReadonlySet<string> = new Set([
  'CFDI_DUPLICATE',
  'CFDI_RFC_FOREIGN',
  'CFDI_UUID_HASH_CONFLICT',
  'CFDI_UUID_INVALID',
  'CFDI_VERSION_UNSUPPORTED',
  'COMPLEMENT_UNSUPPORTED',
  'CONFIGURATION_INVALID',
  'FISCAL_PERIOD_NOT_CONFIGURED',
  'HANDLER_NOT_REGISTERED',
  'IDEMPOTENCY_CONFLICT',
  'IDEMPOTENCY_KEY_EXPIRED',
  'IDEMPOTENCY_KEY_REQUIRED',
  'INGESTION_ACTIVE_JOB_LIMIT',
  'INGESTION_FILE_REQUIRED',
  'INGESTION_FILE_TOO_LARGE',
  'INGESTION_TOO_MANY_FILES',
  'INGESTION_UNSUPPORTED_MEDIA_TYPE',
  'INGESTION_UPLOAD_ABORTED',
  'INVALID_HANDLER_RESULT',
  'JOB_CLAIM_FAILED',
  'JOB_LEASE_LOST',
  'JOB_NOT_RETRYABLE',
  'JOB_RETRY_EXHAUSTED',
  'JOB_ROOT_OBJECT_UNAVAILABLE',
  'JOB_STATE_CONFLICT',
  'MALWARE_DETECTED',
  'MALWARE_SCANNER_ABORTED',
  'MALWARE_SCANNER_HEALTH_TIMEOUT',
  'MALWARE_SCANNER_INVALID_CONFIGURATION',
  'MALWARE_SCANNER_LIMIT_EXCEEDED',
  'MALWARE_SCANNER_PROTOCOL_ERROR',
  'MALWARE_SCANNER_TIMEOUT',
  'MALWARE_SCANNER_UNAVAILABLE',
  'MFA_REQUIRED',
  'MFA_SETUP_REQUIRED',
  'OBJECT_HASH_MISMATCH',
  'OBJECT_STORAGE_CONFLICT',
  'OBJECT_STORAGE_HEALTH_TIMEOUT',
  'OBJECT_STORAGE_INVALID_CONFIGURATION',
  'OBJECT_STORAGE_INVALID_KEY',
  'OBJECT_STORAGE_LIMIT_EXCEEDED',
  'OBJECT_STORAGE_NOT_FOUND',
  'OBJECT_STORAGE_SIZE_MISMATCH',
  'OBJECT_STORAGE_UNAVAILABLE',
  'OBJECT_STORAGE_UNSUPPORTED_OPERATION',
  'ORPHANED_PENDING_OBJECT',
  'PARSER_INTERNAL_ERROR',
  'PERMISSION_REQUIRED',
  'POSTGRES_FISCAL_SCHEMA_NOT_READY',
  'POSTGRES_UNAVAILABLE',
  'RECONCILIATION_CONFLICT',
  'RECONCILIATION_FAILED',
  'REDIS_WAKEUP_UNAVAILABLE',
  'RESOURCE_NOT_FOUND',
  'RLS_CONTEXT_INVALID',
  'RLS_CONTEXT_REQUIRED',
  'UNEXPECTED_WORKER_ERROR',
  'UPLOAD_ALREADY_CONFIRMED',
  'UPLOAD_EXPIRED',
  'UPLOAD_NOT_CONFIRMABLE',
  'UPLOAD_PAYLOAD_MISMATCH',
  'WORKER_SHUTDOWN',
  'WORKER_STATE_TRANSITION_FAILED',
  'WORKER_SUPERVISOR_NOT_RUNNING',
  'WORKER_SUPERVISOR_STALE',
  'WORKER_SUPERVISOR_UNAVAILABLE',
  'XML_MALFORMED',
  'XML_SECURITY_VIOLATION',
]);

/**
 * Validates the shared catalog-backed durable/telemetry error-code contract
 * without ever including the rejected value in the thrown error.
 */
export function assertCanonicalFiscalErrorCode(value: string): void {
  if (!CANONICAL_FISCAL_ERROR_CODES.has(value)) {
    throw new Error('Error code must be a canonical safe token');
  }
}

export function isCanonicalFiscalErrorCode(value: unknown): value is string {
  return typeof value === 'string' && CANONICAL_FISCAL_ERROR_CODES.has(value);
}
