import type { Capability, DemoFixtureSet } from "@/lib/accounting-types";

const titularCapabilities: Capability[] = [
  "organization.view",
  "organization.manage",
  "ownership.manage",
  "billing.manage",
  "team.view",
  "members.manage",
  "permissions.manage",
  "clients.view",
  "clients.manage",
  "clients.assign",
  "fiscal_entities.view",
  "fiscal_entities.manage",
  "fiscal_years.view",
  "fiscal_years.manage",
  "credentials.manage",
  "sat.download",
  "payroll.view",
  "cfdi.exclude",
  "periods.close",
  "periods.reopen",
  "exports.generate",
  "support.authorize",
];

export const demoData: DemoFixtureSet = {
  mode: "demo",
  account: {
    id: "cuenta-demo-mariana",
    name: "Mariana Torres",
    email: "mariana@example.test",
  },
  organizations: [
    {
      id: "estudio-norte",
      slug: "estudio-norte",
      name: "Estudio Contable Norte",
      shortName: "Estudio Norte",
    },
    {
      id: "colectivo-centro",
      slug: "colectivo-centro",
      name: "Colectivo Fiscal Centro",
      shortName: "Colectivo Centro",
    },
  ],
  memberships: [
    {
      organizationId: "estudio-norte",
      role: "titular",
      capabilities: titularCapabilities,
      assignedClientIds: ["comercial-sur", "servicios-bajio", "taller-orion"],
    },
    {
      organizationId: "colectivo-centro",
      role: "colaborador",
      capabilities: [
        "organization.view",
        "clients.view",
        "fiscal_entities.view",
        "fiscal_years.view",
      ],
      assignedClientIds: ["distribuidora-lago"],
    },
  ],
  clients: [
    {
      id: "comercial-sur",
      organizationId: "estudio-norte",
      name: "Comercial del Sur Demo",
      rfc: "DEM010101AA1",
      responsible: "Mariana Torres",
      currentPeriod: "Agosto 2026",
      status: "En revisión",
      progress: 76,
      incidents: 3,
      lastCutoff: "18 ago 2026, 11:42",
      lastActivity: "Hace 18 min",
      eSignature: "Vigente",
      satConnection: "Conectado",
    },
    {
      id: "servicios-bajio",
      organizationId: "estudio-norte",
      name: "Servicios del Bajío Demo",
      rfc: "DEM020202BB2",
      responsible: "Ángel Ruiz",
      currentPeriod: "Agosto 2026",
      status: "Con novedades",
      progress: 92,
      incidents: 1,
      lastCutoff: "17 ago 2026, 16:08",
      lastActivity: "Ayer",
      eSignature: "Próxima a vencer",
      satConnection: "Requiere atención",
    },
    {
      id: "taller-orion",
      organizationId: "estudio-norte",
      name: "Taller Orión Demo",
      rfc: "DEM030303CC3",
      responsible: "Lucía Soto",
      currentPeriod: "Agosto 2026",
      status: "Listo para cerrar",
      progress: 100,
      incidents: 0,
      lastCutoff: "18 ago 2026, 09:10",
      lastActivity: "Hoy, 09:16",
      eSignature: "Vencida",
      satConnection: "Sin configurar",
    },
    {
      id: "distribuidora-lago",
      organizationId: "colectivo-centro",
      name: "Distribuidora del Lago Demo",
      rfc: "DEM040404DD4",
      responsible: "Mariana Torres",
      currentPeriod: "Agosto 2026",
      status: "En preparación",
      progress: 48,
      incidents: 2,
      lastCutoff: "16 ago 2026, 14:20",
      lastActivity: "Hace 2 días",
      eSignature: "Vigente",
      satConnection: "Conectado",
    },
  ],
  periods: [
    {
      month: "Enero",
      slug: "01",
      status: "Cerrado",
      progress: 100,
      cfdi: 312,
      incidents: 0,
      cutoff: "02 feb 2026",
      version: "v1",
      responsible: "Mariana Torres",
    },
    {
      month: "Febrero",
      slug: "02",
      status: "Cerrado",
      progress: 100,
      cfdi: 286,
      incidents: 0,
      cutoff: "03 mar 2026",
      version: "v1",
      responsible: "Mariana Torres",
    },
    {
      month: "Marzo",
      slug: "03",
      status: "Cerrado",
      progress: 100,
      cfdi: 341,
      incidents: 0,
      cutoff: "02 abr 2026",
      version: "v2",
      responsible: "Mariana Torres",
    },
    {
      month: "Abril",
      slug: "04",
      status: "Con novedades",
      progress: 100,
      cfdi: 298,
      incidents: 1,
      cutoff: "04 may 2026",
      version: "v1",
      responsible: "Ángel Ruiz",
    },
    {
      month: "Mayo",
      slug: "05",
      status: "Cerrado",
      progress: 100,
      cfdi: 355,
      incidents: 0,
      cutoff: "03 jun 2026",
      version: "v1",
      responsible: "Ángel Ruiz",
    },
    {
      month: "Junio",
      slug: "06",
      status: "Reabierto",
      progress: 88,
      cfdi: 327,
      incidents: 2,
      cutoff: "05 jul 2026",
      version: "v2",
      responsible: "Ángel Ruiz",
    },
    {
      month: "Julio",
      slug: "07",
      status: "Listo para cerrar",
      progress: 100,
      cfdi: 368,
      incidents: 0,
      cutoff: "06 ago 2026",
      version: "Borrador",
      responsible: "Mariana Torres",
    },
    {
      month: "Agosto",
      slug: "08",
      status: "En revisión",
      progress: 76,
      cfdi: 244,
      incidents: 3,
      cutoff: "18 ago 2026",
      version: "Borrador",
      responsible: "Mariana Torres",
    },
    {
      month: "Septiembre",
      slug: "09",
      status: "Sin iniciar",
      progress: 0,
      cfdi: 0,
      incidents: 0,
      cutoff: "—",
      version: "—",
      responsible: "Mariana Torres",
    },
    {
      month: "Octubre",
      slug: "10",
      status: "Sin iniciar",
      progress: 0,
      cfdi: 0,
      incidents: 0,
      cutoff: "—",
      version: "—",
      responsible: "Mariana Torres",
    },
    {
      month: "Noviembre",
      slug: "11",
      status: "Sin iniciar",
      progress: 0,
      cfdi: 0,
      incidents: 0,
      cutoff: "—",
      version: "—",
      responsible: "Mariana Torres",
    },
    {
      month: "Diciembre",
      slug: "12",
      status: "Bloqueado",
      progress: 0,
      cfdi: 0,
      incidents: 1,
      cutoff: "—",
      version: "—",
      responsible: "Mariana Torres",
    },
  ],
  processes: [
    {
      id: "proc-sat-104",
      type: "Descarga SAT",
      clientId: "comercial-sur",
      period: "Agosto 2026",
      status: "En proceso",
      satStatus: "Procesando solicitud",
      progress: 62,
      requestedBy: "Mariana Torres",
      startedAt: "18 ago, 11:30",
      updatedAt: "Hace 2 min",
      result: "Esperando respuesta del SAT",
    },
    {
      id: "proc-zip-083",
      type: "Carga manual",
      clientId: "servicios-bajio",
      period: "Agosto 2026",
      status: "Con errores",
      progress: 100,
      requestedBy: "Ángel Ruiz",
      startedAt: "18 ago, 10:04",
      updatedAt: "18 ago, 10:07",
      result: "4 XML requieren revisión",
    },
    {
      id: "proc-exp-071",
      type: "Exportación XLSX",
      clientId: "taller-orion",
      period: "Julio 2026",
      status: "Completado",
      progress: 100,
      requestedBy: "Lucía Soto",
      startedAt: "17 ago, 16:40",
      updatedAt: "17 ago, 16:44",
      result: "Disponible hasta 24 ago",
    },
  ],
  cfdi: [
    {
      uuid: "DEMO-8F2A-44C1-91B0",
      clientId: "comercial-sur",
      type: "Ingreso",
      direction: "Emitido",
      rfc: "DEM050505EE5",
      name: "Cliente Mayorista Demo",
      date: "18/08/2026",
      method: "PUE",
      total: 148320.5,
      currency: "MXN",
      status: "Revisado",
      paymentComplement: "No aplica",
    },
    {
      uuid: "DEMO-7C10-31B2-80A4",
      clientId: "comercial-sur",
      type: "Ingreso",
      direction: "Emitido",
      rfc: "DEM060606FF6",
      name: "Operadora Central Demo",
      date: "17/08/2026",
      method: "PPD",
      total: 86340,
      currency: "MXN",
      status: "Con incidencia",
      paymentComplement: "Pendiente",
    },
    {
      uuid: "DEMO-6B09-22A3-72D8",
      clientId: "comercial-sur",
      type: "Pago",
      direction: "Recibido",
      rfc: "DEM070707GG7",
      name: "Proveedora Horizonte Demo",
      date: "16/08/2026",
      method: "PPD",
      total: 45580.75,
      currency: "MXN",
      status: "Pendiente",
      paymentComplement: "Completo",
    },
    {
      uuid: "DEMO-5A08-13D4-63E7",
      clientId: "comercial-sur",
      type: "Nómina",
      direction: "Emitido",
      rfc: "DEM010101AA1",
      name: "Comercial del Sur Demo",
      date: "15/08/2026",
      method: "PUE",
      total: 129800,
      currency: "MXN",
      status: "Cancelado",
      paymentComplement: "No aplica",
    },
  ],
  notifications: [
    {
      id: "n1",
      title: "Descarga SAT en proceso",
      detail: "Comercial del Sur Demo · Agosto 2026",
      kind: "info",
      href: "/organizations/estudio-norte/processes",
      time: "Hace 2 min",
    },
    {
      id: "n2",
      title: "4 XML requieren revisión",
      detail: "Servicios del Bajío Demo",
      kind: "danger",
      href: "/organizations/estudio-norte/processes",
      time: "Hace 1 h",
    },
    {
      id: "n3",
      title: "e.firma próxima a vencer",
      detail: "Servicios del Bajío Demo · 18 días",
      kind: "warning",
      href: "/organizations/estudio-norte/clients/servicios-bajio/settings/e-signature-sat",
      time: "Ayer",
    },
    {
      id: "n4",
      title: "Período listo para cerrar",
      detail: "Taller Orión Demo · Julio 2026",
      kind: "success",
      href: "/organizations/estudio-norte/clients/taller-orion/fiscal-years/2026/periods/07/close",
      time: "Ayer",
    },
  ],
};

export const demoOrganizationId = "estudio-norte";
export const demoClientId = "comercial-sur";
export const demoYear = "2026";
export const demoPeriod = "08";

export function organizationById(id: string) {
  return demoData.organizations.find((organization) => organization.id === id);
}
export function organizationBySlug(slug: string) {
  return demoData.organizations.find(
    (organization) => organization.slug === slug,
  );
}
export function membershipFor(organizationId: string) {
  return demoData.memberships.find(
    (membership) => membership.organizationId === organizationId,
  );
}
export function clientsFor(organizationId: string) {
  const membership = membershipFor(organizationId);
  if (!membership) return [];
  return demoData.clients.filter(
    (client) =>
      client.organizationId === organizationId &&
      membership.assignedClientIds.includes(client.id),
  );
}
export function clientById(organizationId: string, clientId: string) {
  return demoData.clients.find(
    (client) =>
      client.organizationId === organizationId && client.id === clientId,
  );
}
